
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong!Pass123"
    ports:
      - "1433:1433"
    networks:
      - app-network

  backend:
    build: .
    container_name: express-backend
    ports:
      - "3001:3001"
    depends_on:
      - db
    networks:
      - app-network
    environment:
      DB_USER: sa
      DB_PASSWORD: YourStrong!Pass123
      DB_NAME: MyAppDB
      DB_HOST: db

networks:
  app-network:
    driver: bridge
